Adiciona o estudo dos usuários da primeira etapa do Design Sprint
UnBArqDsw2024-2/2024.2_G10_Recomendacao_Entrega_01 pull request #1
Opened 2024-10-25 11:29 UTC by izabellaalves

2024-10-25 23:22 UTC, MatsFidelis approved these changes
Realizado a verificação e teste local das informações adicionadas pela Izabella. 
Erros encontrados foram repassados e devidamente corrigidos.

LGTM!

2024-10-26 00:06 UTC, lucasqueiroz23 requested changes
Ficou muito, muito bom! Só encontrei um pequeno detalhe a ser corrigido. Excelente trabalho! :)

2024-10-26 00:06 UTC, lucasqueiroz23 commented on docs/Base/1.1.DesignSprint.md
> +Para entender melhor os usuários da nossa aplicação e guiar a criação de pessoas baseadas num perfil de usuário, a equipe desenvolveu um questionário que foi respondido por 26 pessoas. Abaixo, nas fi
no caso, aqui não deveria ter a figura 1 (que está acima) e deveria ter a figura 10.

2024-10-26 01:04 UTC, MatsFidelis commented on docs/Base/1.1.DesignSprint.md
> +Para entender melhor os usuários da nossa aplicação e guiar a criação de pessoas baseadas num perfil de usuário, a equipe desenvolveu um questionário que foi respondido por 26 pessoas. Abaixo, nas fi
Realizado a correção e adição de dados referentes à parte de avaliação do concorrente.

Realize uma nova verificação do PR, obrigado.

2024-10-26 01:07 UTC, lucasqueiroz23 approved these changes
ótimo!

2024-10-26 01:08 UTC, merged